accelerate launch infer_conv.py --dataset redial --split train --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_conv 20 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-20_redial_1e-4/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32
accelerate launch infer_conv.py --dataset redial --split valid --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_conv 20 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-20_redial_1e-4/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32
accelerate launch infer_conv.py --dataset redial --split test --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_conv 20 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-20_redial_1e-4/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32



--dataset redial --split train --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 20 --prompt_encoder ../output/conv/dialogpt_prompt-resp_pre_prefix-20_redial_1e-4_repetition/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32
--dataset redial --split valid --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 20 --prompt_encoder ../output/conv/dialogpt_prompt-resp_pre_prefix-20_redial_1e-4_repetition/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32
--dataset redial --split test --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 20 --prompt_encoder ../output/conv/dialogpt_prompt-resp_pre_prefix-20_redial_1e-4_repetition/final --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32



--dataset redial --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 50 --prompt_encoder ../output/pre/unity_relevance/dialogpt_redial_resp_5e_4_repetition/final --num_train_epochs 10 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 8 --per_device_eval_batch_size 16 --num_warmup_steps 6345 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir ../output/conv/unity_relevance_action/dialogpt_redial_resp_1e_4_repetition --discrete_prompt_encoder_relevance ../output/relevance_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_unity ../output/unity_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_action ../output/action_pre/dialogpt_redial_resp_5e-5_repetition/final --use_wandb --project Hybrid_CRS --name conv_unity_relevance_action --log_all --num_conti1 10 --num_conti2 10


#包含relevance和unity
#

--dataset redial --split test --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 50 --prompt_encoder ../output/conv/unity_relevance_action/dialogpt_redial_resp_1e_4_repetition/best_loss --per_device_eval_batch_size 64 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32 --discrete_prompt_encoder_relevance ../output/relevance_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_unity ../output/unity_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_action ../output/action_pre/dialogpt_redial_resp_5e-5_repetition/final  --project Hybrid_CRS --name conv_unity_relevance_action --log_all --num_conti1 10 --num_conti2 10
