accelerate launch train_rec.py --dataset redial_gen --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_rec 20 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_redial-resp_1e-3/final --num_train_epochs 5 --per_device_train_batch_size 64 --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-20_redial_1e-4 --use_wandb --project crs-prompt-rec-final --name dialogpt_prompt-pre_prefix-20_redial_1e-4 --log_all
accelerate launch train_rec.py --dataset redial_gen --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_rec 10 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_redial-resp_1e-3/final --num_train_epochs 5 --per_device_train_batch_size 64 --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-10_redial_1e-4 --use_wandb --project crs-prompt-rec-final --name dialogpt_prompt-pre_prefix-10_redial_1e-4 --log_all
accelerate launch train_rec.py --dataset redial_gen --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_rec 5 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_redial-resp_1e-3/final --num_train_epochs 5 --per_device_train_batch_size 64 --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-5_redial_1e-4 --use_wandb --project crs-prompt-rec-final --name dialogpt_prompt-pre_prefix-5_redial_1e-4 --log_all
accelerate launch train_rec.py --dataset redial_gen --tokenizer ../utils/tokenizer/dialogpt-small --model microsoft/DialoGPT-small --text_tokenizer ../utils/tokenizer/roberta-base --text_encoder roberta-base --n_prefix_rec 3 --prompt_encoder /mnt/wangxiaolei/crs/prompt/dialogpt_redial-resp_1e-3/final --num_train_epochs 5 --per_device_train_batch_size 64 --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir /mnt/wangxiaolei/crs/prompt/dialogpt_prompt-pre_prefix-3_redial_1e-4 --use_wandb --project crs-prompt-rec-final --name dialogpt_prompt-pre_prefix-3_redial_1e-4 --log_all

--dataset redial_gen --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_rec 10 --prompt_encoder ../output/pre/dialogpt_redial-resp_5e-4_repetition/final --num_train_epochs 5 --per_device_train_batch_size 64  --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir ../output/rec/dialogpt_redial-rec_pre_prefix-20_redial_1e-4_repetition --use_wandb --project UniCRS_rec --name dialogpt_redial-rec_pre_prefix-20_redial_1e-4_repetition --log_all  # wandb experiment name




--dataset redial --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_conv 50 --prompt_encoder ../output/pre/unity_relevance/dialogpt_redial_resp_5e_4_repetition/final --num_train_epochs 10 --gradient_accumulation_steps 1 --ignore_pad_token_for_loss --per_device_train_batch_size 8 --per_device_eval_batch_size 16 --num_warmup_steps 6345 --context_max_length 200 --resp_max_length 183 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir ../output/conv/unity_relevance/dialogpt_redial_resp_1e_4_repetition --discrete_prompt_encoder_relevance ../output/relevance_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_unity ../output/unity_pre/dialogpt_redial_resp_5e-5_repetition/final --use_wandb --project EmoCRS --name pre_conv_unity_relevance --log_all





--dataset redial_gen --tokenizer ../model/DialogGPT --model ../model/DialogGPT --text_tokenizer ../model/roberta-base --text_encoder ../model/roberta-base --n_prefix_rec 10 --prompt_encoder ../output/pre/unity_relevance_action/dialogpt_redial_resp_5e_4_repetition/final --num_train_epochs 10 --per_device_train_batch_size 64  --per_device_eval_batch_size 64 --gradient_accumulation_steps 1 --num_warmup_steps 530 --context_max_length 200 --prompt_max_length 200 --entity_max_length 32 --learning_rate 1e-4 --output_dir ../output/rec/unity_relevance_action/dialogpt_redial_resp_1e_4_repetition --discrete_prompt_encoder_relevance ../output/relevance_pre/dialogpt_redial_resp_5e-5_repetition/final --discrete_prompt_encoder_unity ../output/unity_pre/dialogpt_redial_resp_5e-5_repetition/final  --discrete_prompt_encoder_action ../output/action_pre/dialogpt_redial_resp_5e-5_repetition/final --num_conti1 15 --num_conti2 15  --project  Hybrid_CRS --name rec_unity_relevance_action --log_all  --use_resp
